<a href="https://colab.research.google.com/github/krushnathakare2007-netizen/Assignment14/blob/main/Task14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
#Array Properties
import numpy as np
arr=np.random.randint(10,101,(5,6))

#Shape of the array
print("Array \n :",arr)
print("Shape :",arr.shape)
print("Size :",arr.size)
print("Data Type :",arr.dtype)


Array 
 : [[32 97 90 91 12 81]
 [80 87 13 75 20 78]
 [46 25 68 72 12 96]
 [67 65 95 29 62 47]
 [64 61 60 23 61 27]]
Shape : (5, 6)
Size : 30
Data Type : int64


In [36]:
#Statistical Methods - Basic
import numpy as np
arr=np.random.randint(1,51,20)

print(arr)

#Minimum value and its index (argmin)
print("Minimum value :",np.min(arr))
print("Minimum value index :",np.argmin(arr))

#Maximum value and its index (argmax)
print("Maximum value :",np.max(arr))
print("Maximum value index :",np.argmax(arr))

#Sum of all elements
print("Sum :",np.sum(arr))

#Mean and Standard Deviation
print("Mean :",np.mean(arr))
print("Standard Deviation :",np.std(arr))


[28 13  7  9 13 18 48 40 28 27 29 17 44  1 37  1 33 43  7 43]
Minimum value : 1
Minimum value index : 13
Maximum value : 48
Maximum value index : 6
Sum : 486
Mean : 24.3
Standard Deviation : 14.926821496889417


In [11]:
#Statistical Methods on 2D Array
import numpy as np
arr=np.random.randint(20,81,(4,5))
print(arr)

#Minimum and maximum value
print("Minimum value :",np.min(arr))
print("Maximum value :",np.max(arr))

#Sum of all elements
print("Sum :",np.sum(arr))

#Mean and Standard Deviation
print("Mean :",np.mean(arr))
print("Standard Deviation :",np.std(arr))

print("Row Sum :",np.sum(arr,axis=1))
print("Column Sum :",np.sum(arr,axis=0))


[[22 44 45 50 30]
 [74 71 70 23 27]
 [50 46 20 37 37]
 [55 55 80 62 46]]
Minimum value : 20
Maximum value : 80
Sum : 944
Mean : 47.2
Standard Deviation : 17.503142574977787
Row Sum : [191 265 190 298]
Column Sum : [201 216 215 172 140]


In [37]:
#Reshape
import numpy as np
arr=np.arange(1,25)
print("Array \n :",arr)

#Reshape it into (4, 6)
a=arr.reshape(4,6)
print("Reshaped Array \n :",a)
print("Shape :",a.shape)

#Reshape it into (3, 8)
b=arr.reshape(3,8)
print("Reshaped Array \n :",b)
print("Shape :",b.shape)

#Reshape it into (2, 3, 4) (3D array)
c=arr.reshape(2,3,4)
print("Reshaped Array \n :",c)
print("Shape :",c.shape)

Array 
 : [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
Reshaped Array 
 : [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
Shape : (4, 6)
Reshaped Array 
 : [[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]
Shape : (3, 8)
Reshaped Array 
 : [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Shape : (2, 3, 4)


In [38]:
#NumPy Indexing - 1D & 2D
import numpy as np
arr = np.array([[10, 20, 30, 40],
[50, 60, 70, 80],
[90, 100, 110, 120]])

print("Array :\n",arr)

#Perform the following indexing:
#Extract first row
print("\nFirst Row :")
print(arr[0])

#Extract last column
print("\nLast Column :")
print(arr[:,-1])

#Extract center 2x2 submatrix
print("\nCenter 2x2 Submatrix :")
print(arr[1:3,1:3])

#Extract all even numbers from the array using boolean indexing
print("\nEven Numbers :")
print(arr[arr%2==0])

Array :
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]

First Row :
[10 20 30 40]

Last Column :
[ 40  80 120]

Center 2x2 Submatrix :
[[ 60  70]
 [100 110]]

Even Numbers :
[ 10  20  30  40  50  60  70  80  90 100 110 120]


In [39]:
#Advanced Indexing
import numpy as np
arr=np.random.randint(1,101,(5,5))
print(arr)

#The diagonal elements
print("\n Diagonal elements :")
print(np.diag(arr))

#Elements greater than 50
print("\n elements greater than 50 :")
print(arr[arr>50])

#Replace all elements less than 30 with 0
arr[arr<30]=0

print("\n Modified Array :")
print(arr)


[[ 51  60   9  87  16]
 [ 41  34  64  37  28]
 [ 65   5  35  18  96]
 [ 16  92  96  76 100]
 [ 49  38  73  86  42]]

 Diagonal elements :
[51 34 35 76 42]

 elements greater than 50 :
[ 51  60  87  64  65  96  92  96  76 100  73  86]

 Modified Array :
[[ 51  60   0  87   0]
 [ 41  34  64  37   0]
 [ 65   0  35   0  96]
 [  0  92  96  76 100]
 [ 49  38  73  86  42]]


In [40]:
#Arithmetic Operations
import numpy as np
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

#Perform and print:
#Addition, Subtraction, Multiplication, Division
print("\n Addition :")
print(a+b)

print("\n Subtraction :")
print(a-b)

print("\n Multiplication :")
print(a*b)

print("\n Division :")
print(a/b)

#Element-wise power (**)
print("\n Element-wise power :")
print(a**b)

#Modulo operation (%)
print("\n Modulo :")
print(a%b)


 Addition :
[11 22 33 44]

 Subtraction :
[ 9 18 27 36]

 Multiplication :
[ 10  40  90 160]

 Division :
[10. 10. 10. 10.]

 Element-wise power :
[     10     400   27000 2560000]

 Modulo :
[0 0 0 0]


In [41]:
#Matrix Multiplication
import numpy as np
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[9,8,7],[6,5,4],[3,2,1]])

#Perform:
#Element-wise multiplication (*)
print("\n Element-wise multiplication :")
print(A*B)

#Matrix multiplication (@ or np.dot())
print("\n Matrix multiplication :")
print(A@B)
print(np.dot(A,B))

#Difference
# * Performs elements wise multiplication
# @ (or np.dot())performs actual matrix multiplication



 Element-wise multiplication :
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]

 Matrix multiplication :
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [42]:
#Combined - Properties + Operations + Indexing
import numpy as np

#Generate a 6x6 matrix of random numbers using np.random.randn().
arr=np.random.randn(6,6)
print("\n matrix \n :",arr)

#Print its shape, size, and dtype.
print("\n Shape :",arr.shape)
print("\n size :",arr.size)
print("\n Data type :",arr.dtype)

#Find the index of the maximum and minimum value.
print("\n Index of Maximum value :",np.argmax(arr))
print("\n Index of Maximum value :",np.argmin(arr))

#Extract the top-left 3x3 submatrix.
print("\n Top-left 3x3 submatrix :")
print(arr[:3,:3])

#Replace all negative numbers with their absolute value.
arr[arr<0]=np.abs(arr[arr<0])

print("\n Modified matrix :")
print(arr)

#Print the mean of the modified matrix.
print("\n Mean :",np.mean(arr))


 matrix 
 : [[ 7.69988626e-01  7.60575770e-01 -3.42864095e-01  1.45940704e+00
  -2.14225630e-01 -7.53897363e-01]
 [ 1.52087611e-01  3.41108616e-01  6.94753293e-02 -1.25889220e-02
   1.49248254e-01 -7.64097531e-02]
 [ 1.28872015e+00  5.94681681e-02  1.98023761e+00 -1.86760471e+00
   1.27556152e+00 -1.57992247e-01]
 [ 1.78478033e+00 -6.74913923e-01 -1.04029361e+00 -5.76890605e-01
  -7.02918824e-02  9.20796121e-01]
 [ 5.57308305e-01 -3.34266612e-02  5.39768241e-04  1.88989668e+00
  -1.79315263e+00 -4.67734349e-01]
 [ 1.47645581e+00  9.85994338e-01  1.95984737e-01 -6.89267524e-01
  -1.36849224e+00 -6.16403375e-02]]

 Shape : (6, 6)

 size : 36

 Data type : float64

 Index of Maximum value : 14

 Index of Maximum value : 15

 Top-left 3x3 submatrix :
[[ 0.76998863  0.76057577 -0.3428641 ]
 [ 0.15208761  0.34110862  0.06947533]
 [ 1.28872015  0.05946817  1.98023761]]

 Modified matrix :
[[7.69988626e-01 7.60575770e-01 3.42864095e-01 1.45940704e+00
  2.14225630e-01 7.53897363e-01]
 [1.52087

In [43]:
#Mini Project - Student Performance Analysis
import numpy as np
#Generate marks for 10 students and 5 subject
marks=np.random.randint(30,101,(10,5))
print("Student Marks :\n")
print(marks)

#Total marks of each student
total=np.sum(marks,axis=1)
print("\n Total Marks :\n",total)

#Average marks of each subject
avg=np.mean(marks,axis=1)
print("\n Average Marks :\n",avg)

#Student with highest and lowest total  marks
highest=np.argmax(total)
lowest=np.argmin(total)

#Overall class statistics
print("\n Class Mean :",np.mean(marks))
print("Class Standard Deviation :",np.std(marks))

#Top 3 student based on total marks
top3=np.argsort(total)[-3:]

print("\n Top 3 Students :\n")
print(top3)

print("\nMarks of Top 3 Students :\n")
print(marks[top3])

Student Marks :

[[92 73 77 68 82]
 [68 37 50 33 93]
 [55 94 40 41 98]
 [63 93 46 85 46]
 [72 36 56 80 77]
 [83 43 98 43 55]
 [40 38 86 74 64]
 [75 59 36 87 59]
 [36 64 58 43 46]
 [72 82 49 82 40]]

 Total Marks :
 [392 281 328 333 321 322 302 316 247 325]

 Average Marks :
 [78.4 56.2 65.6 66.6 64.2 64.4 60.4 63.2 49.4 65. ]

 Class Mean : 63.34
Class Standard Deviation : 19.75004810120725

 Top 3 Students :

[2 3 0]

Marks of Top 3 Students :

[[55 94 40 41 98]
 [63 93 46 85 46]
 [92 73 77 68 82]]
